services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:8080"
    # environment:
    #   - PORT=8080
    #   - MONGO_URI=mongodb://host.docker.internal:27017/major_project
    #   - JWT_ACCESS_TOKEN_SECRET=fdhfgshjkdgfvhkgddsfjgdshffyhsdfgysdhjfvdgfvsdjhfvs
    #   - JWT_ACCESS_TOKEN_EXPIRE=2d
    #   - JWT_REFRESH_TOKEN_SECRET=fdhfgshjkdgfvhkgddsfjgdshffyhsdfgysdhjfvdgfvsdjhfvs
    #   - JWT_REFRESH_TOKEN_EXPIRE=10d
    env_file:
      - .env